[workspace]
members = ["truehd", "truehdd-macros"]
resolver = "2"

[package]
name = "truehdd"
version = "0.5.0"
edition = "2024"
license = "Apache-2.0"
description = "Tools for inspecting and decoding Dolby TrueHD bitstreams"
repository = "https://github.com/truehdd/truehdd"
build = "build.rs"
authors = ["Rainbaby"]
rust-version = "1.95.0"

[[bin]]
name = "truehdd"
path = "src/main.rs"

[dependencies]
truehdd-macros = { version = "0.1.0", path = "truehdd-macros" }
truehd = { version = "0.5.0", path = "truehd" }

anyhow = "1.0.104"
clap = { version = "4.6.4", features = ["derive"] }
crossbeam = "0.8.4"
env_logger = "0.11.11"
indicatif = "0.18.6"
indicatif-log-bridge = "0.2.3"
log = "0.4.33"
serde = { version = "1.0.229", features = ["derive"] }
serde_yaml_ng = "0.10.0"

[dev-dependencies]
tempfile = "3.27.0"

[build-dependencies]
anyhow = "1.0.104"
vergen-gitcl = { version = "10.0.1", default-features = false, features = ["build"] }
chrono = "0.4.45"
serde_json = "1.0.151"

[profile.release-deploy]
inherits = "release"
lto = "thin"
strip = "symbols"
